name: C/C++ Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Build Tools
      run: sudo apt-get install -y build-essential

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake ..
        make
