name: C/C++ CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
     start: npm start
     start-windows: npm run start:ci:windows
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
