name: C/C++ CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
my_first_job:
name: My first job
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

my_second_job:
  name: My second job
    - name: Cache
      uses: actions/cache@v3.3.2
      with: .\src\about.c
    path: .\src\about.c
    key: cache-hit
          