name: C CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: scons debhelper intltool libgtk-4-dev libadwaita-1-dev libxml2-dev libcurl4-gnutls-dev libgconf2-dev gettext
          version: 1.0

  build-app:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flatpak environment
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y flatpak-builder flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.gnome.Sdk//43
          sudo flatpak update -y
          sudo flatpak install -y flathub org.freedesktop.Platform.GL.default//23.08
          sudo apt-get install -y

      - name: Flatpak Builder
        uses: flatpak/flatpak-github-actions@v6.3

      - name: Build
        run: scons
 
      - name: Deploy
        run: scons install
      
