name: C/C++ CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
       uses: actions/cache@v3.3.2
       with:
         path: 
         key: 
         enableCrossOsArchive: true
         lookup-only: true
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: test
        path: .github\workflows
          