name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
 
  BUILD_TYPE: TestBuild

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: .

    - name: Build
      run: .\glosung\src

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

          